---
- name: Install Java
  hosts: all
  roles:
    - java
  tags:
    - java

- name: Install Elasticsearch
  hosts: elasticsearch
  roles:
    - elastic-role
  tags: 
    - elastic

- name: Install Kibana
  hosts: kibana
  roles:
    - kibana-role
  tags:
    - kibana